### ISSUE TITLE
Background scan

### ISSUE THREAD

**Issue by remydavid** [AltBeacon/android-beacon-library-reference#3]
Hello,

The RegionBootstrap doc states: 
    The RegionBootstrap class registers an internal MonitorNotifier with the BeaconManager.   If you use the RegionBootstrap, your application must not manually register a second MonitorNotifier, otherwise it will unregister the one configured by the RegionBootstrap, effectively disabling it.  When using the RegionBootstrap, any custom monitoring code must must therefore be placed in the callback methods in the BootsrapNotifier implementation passed to the RegionBootstrap.

However, the reference application does register a second MonitorNotifier in the MonitoringActivity onBeaconServiceConnect.  

Can you clarify ?

Thanks

**Comment by davidgyoung** [comment]
You are absolutely correct, @remydavid, thanks for the catch.  The documentation is correct, and the ReferenceApplication essentially disables the RegionBootstrap as soon as the MonitoringActivity is launched.  I know better, but had not noticed that I did this when I modified the open source library's reference application to use the RegionBootstrap feature, which was formerly not part of the open source library.

Fixed in 852b4364f982cb247e9a18c2d5c56365bc4a7586
