### ISSUE TITLE
Library compatibility with Android O

### ISSUE THREAD

**Issue by aashu09** [AltBeacon/android-beacon-library-reference#36]
Hi,

I have a question about this library i.e. 
Is this library compatible with "android-beacon-library-2.12.aar" ?

android-beacon-library-2.12.aar is necessary for Android O Support.

Please response.

**Comment by davidgyoung** [comment]
Yes, library versions 2.12+ are compatible with Android 8.0+. If using an earlier library version with Android 8.0+ you will not be able to detect beacons for more than 15 minutes after your app was last in the foreground.

**Comment by aashu09** [comment]
yes that's nice but my question is other, I mean that Is this reference
sample compatible with new 2.12 library ? i.e. in this reference code, old
altbeacon library is used but I need the sample code with use of 2.12
library.

**Comment by davidgyoung** [comment]
This reference app works out of the box with 2.12+.    The build.gradle file automatically pulls in the latest library version (2.12.1 as of this writing) which is matched by this line:

```
    compile 'org.altbeacon:android-beacon-library:2+'
```

The reference app has not yet been updated to *target*  the SDK for Android 8.0 because the build tools are still in beta.   That said, you can still use the existing reference app setup with targetSdkVersion 25 and deploy and run the output app on Android 8 devices.  This is because the binary library it uses is pre-built to work with Android 8.

**Comment by aashu09** [comment]
that means by the same peace of code, We use for earlier Android versions,
is the same in Android O or we have to apply any other code ?

I have read about some checks to work with Android O. Is any check needed ?

On 17-Aug-2017 8:25 PM, "David G. Young" <notifications@github.com> wrote:

This reference app works out of the box with 2.12+. The build.gradle file
automatically pulls in the latest library version (2.12.1 as of this
writing) which is matched by this line:

    compile 'org.altbeacon:android-beacon-library:2+'

The reference app has not yet been updated to *target* the SDK for Android
8.0 because the build tools are still in beta. That said, you can still use
the existing reference app setup with targetSdkVersion 25 and deploy and
run the output app on Android 8 devices. This is because the binary library
it uses is pre-built to work with Android 8.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AltBeacon/android-beacon-library-reference/issues/36#issuecomment-323097669>,
or mute the thread
