### ISSUE TITLE
Monitoring not working in the reference app?

### ISSUE THREAD

**Issue by ProsperousBloom** [AltBeacon/android-beacon-library-reference#44]
Hi,

Using Android 8.1.

I'm testing the reference app and since there is no direct usage of monitoring, only the regionBootstrap?
And that is not working for me. I added the iBeacon layout. And doing RANGING I can find the beacons, but the didEnterRegion, didExitRegion events from the BeaconReferenceApplication.java are never triggered. I was expecting to see some use of 

    beaconManager.startMonitoringBeaconsInRegion(region);

However, there is nothing like it in the app? Is the RegionBootstrap supposed to take care of it? Because it isn't. In another app I made I used startMonitoringBeaconsInRegion specifically and that seemed to work, but not in combination with the RegionBootstrap.

**Comment by davidgyoung** [comment]
@ProsperousBloom, it's really hard to troubleshoot issues like this without seeing the code you are using to set up monitoring.  I'd suggest you post a new question on StackOverflow.com.  This the preferred forum for troubleshooting project-specific problems so we can keep this forum clean for bugs and feature requests.  Please make a question that shows your monitoring setup code and callbacks (including the context of what classes these are in)  and then describe how you test it and what you see that is not what you expect.  A logcat except would likely be helpful showing what callbacks you get and what ones you don't.  

RegionBootstrap calls startMonitoringBeaconsInRegion internally, which is why you don't see it in the reference app.  But it is there -- it is just one layer down.

If you create the question on StackOverflow, I'll take a look.  If we find there is any problem with the library we can open an issue here at that time.
