### ISSUE TITLE
when beacon out of range , I see beacon notification

### ISSUE THREAD

**Issue by hearbeathorror** [AltBeacon/android-beacon-library-reference#5]
Hi

I am using this library and the library-reference app. I managed to listen to a custom beacon using the set beacon layout method. 

Step1. I set the layout in the application class
Step 2. I mke the baseactivity implement beaconconsume where it performs ranging.

When starting the range monitoring service/method we use "myRangeUniqueId" but the didexit and didenter methods use "backgroundId" I think. Why is that so?

So the situation is this
I move the beacon device some few meters away , I still get I see a beacon notification and I do not see a beacon.. These messages keep changing alternatively even when the beacon is far.

Do I have to do anything to prevent this? Please help.

Thanks

**Comment by hearbeathorror** [comment]
Also... When exiting a region can in determine which beacon is exiting? Please help.

**Comment by davidgyoung** [comment]
The preferred forum for questions on how to use this library is to open a question on Stackoverflow.com.  This forum is reserved for feature requests and reproducible bugs with the library itself.

The cause of your problem is not clear, so if you post to Stackoverflow.com, please include a snippet of your code that sets up ranging and monitoring as well as the code of your callback method.  Also please describe how you are determining which of the ids you mention are being provided to the callback methods.

**Comment by hearbeathorror** [comment]
@davidgyoung  - Sir do you mind answering this one for me please? http://stackoverflow.com/questions/29002037/how-to-identify-which-beacon-is-exiting-beacon-notification-seen-when-beacon-is 

I have an app that is held up because it is not able to recognize beacons properly unlike the way it is in  iOS . Thanks

**Comment by davidgyoung** [comment]
Answered in linked forum

**Comment by hearbeathorror** [comment]
@davidgyoung  - Sir, i see multiple exit and entry logs even when the beacon device is pretty close to the device i am using to detect it, please have a look at the stack overflow question here... [here](http://stackoverflow.com/questions/29159614/beacons-didenterregion-and-didexitregion-repeatedly-called)
